CREATE TABLE IF NOT EXISTS ai_generations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  prompt TEXT NOT NULL,
  target_ids TEXT NOT NULL,
  desired_count INTEGER NOT NULL DEFAULT 100,
  batch_size INTEGER NOT NULL DEFAULT 3,
  generated_count INTEGER NOT NULL DEFAULT 0,
  model TEXT NOT NULL,
  previous_outputs TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
